### PR TITLE
Try Python 3.10

### PR DESCRIPTION
**Pull request by bendichter**
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208161143099980
  - https://app.asana.com/0/0/1208161143099988

### CODE REVIEW

**Comment by bendichter** [comment]
@vinicvaz I'm attempting to expand our environment to include Python 3.10 so this can be easily run on Google Colab I also think it's good to have this be able to run on more than a single version of Python if possible. The tests are failing but it looks like it might be just due to the way the tests were written. It looks like you may be using a newer feature of `patch`. Would it be possible to write these files without using `patch`? Maybe storing the config as a tempfile would be more straightforward?

**Comment by bendichter** [comment]
@vinicvaz I've also modified the CI so that the tests run on PRs. This is the standard way to do it so you know if tests fail *before* you merge ;-)

**Comment by vinicvaz** [comment]
@bendichter if the problem is just the tests we can find a way to replace what are conflictant. I don't think removing the patch mocks to a config file is a good options,, there are some tests we need to override some settings or arguments on the fly to make.
I don't know why but my github is not showing the entire logs in the actions (as shown in the image below) so I didn't see what exactly is failing. Can you see the entire log?

image

**Comment by vinicvaz** [comment]
@bendichter about the CI, great, thanks for fixing this. If I'm not wrong we were running the tests only from dev because of the github 2000 minutes / month limit for free accounts. When we were actively commiting on multiple branches we could potentially reach this limit since the tests can take some time to run and we have 3 OS to test.

**Comment by luiztauffer** [comment]
the reason why Python 3.10 was requested is because that is the default version in Google Colab. But this is about to change: https://github.com/googlecolab/colabtools/issues/4935

I suggest we keep supporting Python >= 3.11

**Review by ThanabodeeOiuwattana — APPROVED** [review]

**Pull request closed without merging**
