### PR TITLE
Add docs

### PR DESCRIPTION
**Pull request by vinicvaz**
This PR is adding the following:
- [x] Docstrings to all methods in VAME package
- [x] Typing annotation in all functions definitions in VAME package
- [x] Docs app - Adding basic docusaurus app for VAME project
- [x] Docs API Reference - Add VAME python API Reference in docs app.
- [x] FAQ docs section 

**This is not the final version of the documentation app, but rather an initial iteration that defines a structure we can utilize to  enhance the organization and documentation of the package**

### Running the docs app
Go to `/docs/vame-docs-app` and run 
```
yarn
yarn start
```
**Suggested to run using node >18**

Example screenshots of docs app:

image
image
image
image

### CODE REVIEW

**Comment by bendichter** [comment]
I'd rather not commit all of the generated docs files. Is there a workflow that allows us to not commit those into the main branch?

**Comment by bendichter** [comment]
Could you change all docstring to use double quotes? This is a [PEP8 convention](https://peps.python.org/pep-0008/#string-quotes)

**Comment by bendichter** [comment]
This looks great! Just a few minor points.

**Comment by bendichter** [comment]
Also, it would be helpful to set up a GitHub action to render a preview of the docs

**Comment by bendichter** [comment]
See the GitHub Action files here: https://docusaurus.io/docs/deployment#triggering-deployment-with-github-actions

**Comment by luiztauffer** [comment]
> I'd rather not commit all of the generated docs files. Is there a workflow that allows us to not commit those into the main branch?

I think we could just generate the API Reference markdown files in the action and they'd exist in `gh-pages` branch. But what do we gain from that? We would loose the option to check for docs updates at PR reviews, whenever the Python API changes, for example.

**Comment by vinicvaz** [comment]
> Also, it would be helpful to set up a GitHub action to render a preview of the docs

Hey @bendichter , here is the github page for the docs: https://ethoml.github.io/VAME/

There are few things to fix in the docs, like:
- Landing page using docusaurus hero colors and features images
- Remove docusaurus favicon and use a vame
- Get a nice vame logo to use as navbrand
- Decide if keep the blog page, if so, set the name of the authors that will write there.

But of course, this are things that we can keep improving and defining together.

**Comment by vinicvaz** [comment]
> I'd rather not commit all of the generated docs files. Is there a workflow that allows us to not commit those into the main branch?

About this I'm not sure what would be the best approach in this case... I understand your point and honestly I also don't like the idea of having the entire docs app in the main branch since it is not part of the package, but also I'm thinking about the cycle of updating/developing the docs.
Maybe an option is to have a specific docs branch called `/docs` to store everything, the package and the docs app, and let all the other branches ignoring the folder `/docs`.
With this branch we can:
- pr/merge main into it when package changes so the docs can be automatically generated and deployed
- use the branch as base to develop docs pages and features

All the other branches would be based on main and ignore `/docs` folder.
The only problem with this is to keep the consistency between the `.gitignore` files

This is just an idea, we can discuss about other options too but let me know your thoughts on that @luiztauffer @bendichter

**Comment by bendichter** [comment]
The website looks great! I agree with the to-do.

I see you have already created a gh-pages with the generated code. That's another standard approach and would be fine with me. However, the generated pages should not be edited directly. If you do that, then you'll lose all of those edits as a soon as you re-generate. If we do that then we should remove the generated files from this branch. I'd like to avoid having them in the git history of the main branch

**Comment by bendichter** [comment]
But either way, could you still try to put a GH Action for a docs preview together?

**Comment by vinicvaz** [comment]
> The website looks great! I agree with the to-do.
> 
> I see you have already created a gh-pages branch with the generated code. That's another standard approach and would be fine with me. However, the generated pages should not be edited directly. If you do that, then you'll lose all of those edits as a soon as you re-generate. If we do that then we should remove the generated files from this branch. I'd like to avoid having them in the git history of the main branch

Sure, we are deploying to github pages from the `gh-pages` branch that is receiving the docs **build files** from the github workflow.
I'll create a previous action to run and automatically to generate the markdown files for the api reference.

**Comment by vinicvaz** [comment]
> But either way, could you still try to put a GH Action for a docs preview together?

sorry, what you mean by the preview? the action to test the docs build or what?

**Comment by bendichter** [comment]
For any PR, I want the docs to build and I want to be able to see what the new docs look like by pressing a button here

image

These docs describe how to do that: https://docusaurus.io/docs/deployment#triggering-deployment-with-github-actions

**Comment by bendichter** [comment]
Also, the GitHub link currently goes to the Docusourus GitHub. Can we change that to the VAME repo?

**Comment by vinicvaz** [comment]
> For any PR, I want the docs to build and I want to be able to see what the new docs look like by pressing a button here

Got it but I'm not sure if it is possible using github pages only. There is a long discussion about this feature in this [link](https://github.com/orgs/community/discussions/7730#discussioncomment-7603270) and this [issue](https://github.com/actions/deploy-pages/issues/180). The docusaurus link you sent me is more related to a build test validation, not a preview I guess.
Using external services, like vercel or others which lets us use extra servers to host the page we can create a "staging" environment for the PR preview.

I've also find this interesting repository that might help us https://github.com/rossjrw/pr-preview-action, but:
* looks like it does not work on forks, the support is comming in v2
* I'm not sure how it would work since it will use the same base url of the main docs but with a extra path path, ex: https://ethoml.github.io/VAME/pr-preview-action/my-new-pr . It might be accessible on the same docs url, that is not a big problem but would be better to have it in a different subdomain.

Maybe I'm missing something here but let me know what you think

**Comment by vinicvaz** [comment]
> Maybe this one? https://github.com/marketplace/actions/build-deploy-to-github-pages-and-deploy-pr-preview#docusaurus
> 
> If this is hard we can skip it and come back to it later.
> 
> I like the idea of the blog. I think Steph could write a post about the paper there, and it would be a good place to highlight labs using VAME for different projects.

this looks promising, I'll take a look, thanks!

**Comment by vinicvaz** [comment]
@bendichter what you think about closing this pr, deleting this branch and splitting it into two different branches, being them:
- 1. One with the updates for the package
- 2. `docs` branch with the isolated docs app

This will ensure that we are not sending the docs app to the dev or main branches.

**Comment by bendichter** [comment]
sure

**Pull request closed without merging**
